spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_db
    username: postgres
    password: qwerty123
    driver-class-name: org.postgresql.Driver

  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: XyZ123Abc456Def789Ghi012Jkl345Mno678Pqr901Stu234Vwx567Zab890Cde123Fgh456Ijl789Klm012Nop345Qrs678Tuv901Wxy234Zab567Cde890Fgh123Ijk456Lmn789Opq012Rst345Uvw678Xyz901

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
